server:
  port: 8082
spring:
  application:
    name: csn-saga-base
  datasource:
    url: jdbc:mysql://localhost:3306/cloopm_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: hapcloud
    password: handhand